Fix missing Redis password
- Fix below issue:
```
Traceback (most recent call last):
  File "/var/www/djangoplay/.venv/lib/python3.11/site-packages/environ/environ.py", line 409, in get_value
    value = self.ENVIRON[var_name]
            ~~~~~~~~~~~~^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'REDIS_PASSWORD'
```